### ISSUE TITLE
Text cursor remains persistent and won't go away

### ISSUE THREAD

**Issue by ryanaltvater** [rampatra/todobar-community#4]
![Screenshot 2024-11-01 at 4 59 33 PM](https://github.com/user-attachments/assets/6c457bbc-5b8a-4153-90a7-fadf218926f8)

**Steps to reproduce:**
1. Open the app
2. Click into a task, to reveal the text cursor
3. Click out of the task list
4. Click back into the task list
5. Text cursor visible

**Comments:**
This led me to hit Esc as a natural behavior of unfocusing a thing that's actively focused, and that unintentionally deleted my task. This has happened a few times.

**Comment by rampatra** [comment]
The fix for https://github.com/rampatra/todobar-community/issues/3 should address this as well.

**Comment by ryanaltvater** [comment]
Excellent, thank you!

**Comment by rampatra** [comment]
This issue has been addressed in version 2.0.0 (released a few days ago). Can you pl kindly update the app and check this? If you're happy, please close this after.

**Comment by ryanaltvater** [comment]
I'm still seeing this issue. I click into a task, click out of the app to close it, open it back up, and my cursor is still where it was when I previously clicked into the task. Same as the latest comment I just made on issue #3.

**Comment by rampatra** [comment]
https://github.com/user-attachments/assets/d2ed02d9-109c-4b61-8468-9c529738dfb9

This is what the behavior is for me. What macOS version are you using? Also, I would suggest restarting the app after you updated it. And, make sure you don't have multiple versions of the app.

**Comment by ryanaltvater** [comment]
I never got around to installing the TestFlight version before you released 2.0. So I only have the one version of the app, of which I've exited out of multiple times and I'm still experiencing the issue.

![Screenshot 2024-11-14 at 6 07 54 PM](https://github.com/user-attachments/assets/b81eb740-3ad1-4c22-ab84-02205f333488)

**Comment by ryanaltvater** [comment]
I have just completely uninstalled the app and reinstalled it. I'm still seeing all of the issues I've reported back on.

**Comment by rampatra** [comment]
What MacBook and macOS version are you using?

**Comment by ryanaltvater** [comment]
M3 Max
